name: docker_jupyter_example
services:
  jupyter:
    build:
      dockerfile: ./Dockerfile
      args:
        JUPYTER_USERNAME: ${JUPYTER_USERNAME}
        UID: ${UID}
        GID: ${GID}
    image: workspace/jupyter
    container_name: jupyter
    user: ${UID}:${GID}
    command: jupyter notebook --port ${JUPYTER_PORT} --no-browser --ip=0.0.0.0
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      JUPYTER_ENABLE_LAB: ${JUPYTER_ENABLE_LAB}
      JUPYTER_USERNAME: ${JUPYTER_USERNAME}
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    volumes:
      - ./data:/home/${JUPYTER_USERNAME}/data:rw
      - ./notebooks:/home/${JUPYTER_USERNAME}/notebooks:rw
