name: docker_jupyter_example
services:
  jupyter:
    build:
      dockerfile: ./Dockerfile
    image: workspace/jupyter
    container_name: jupyter
    user: root
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      JUPYTER_ENABLE_LAB: ${JUPYTER_ENABLE_LAB}
      JUPYTER_USERNAME: ${JUPYTER_USERNAME}
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      NB_UID: ${NB_UID}
      NB_GID: ${NB_GID}
    volumes:
      - ./data:/home/${JUPYTER_USERNAME}/work/data