name: docker_jupyter_example
services:
  jupyter:
    build:
      dockerfile: ./Dockerfile
      args:
        JUPYTER_USERNAME: ${JUPYTER_USERNAME-jovyan}
        UID: ${UID-1000}
        GID: ${GID-1000}
    image: workspace/jupyter
    container_name: jupyter
    user: ${UID-1000}:${GID-1000}
    command: jupyter notebook --port 8888 --no-browser --ip=0.0.0.0
    ports:
      - "${JUPYTER_PORT-8888}:8888"
    environment:
      JUPYTER_ENABLE_LAB: ${JUPYTER_ENABLE_LAB-yes}
      JUPYTER_USERNAME: ${JUPYTER_USERNAME-jovyan}
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      JUPYTER_PORT: ${JUPYTER_PORT-8888}
    volumes:
      - ./data:/home/${JUPYTER_USERNAME-jovyan}/data:rw
      - ./notebooks:/home/${JUPYTER_USERNAME-jovyan}/notebooks:rw
